use std::marker::PhantomData;

use crate::{
    alerts::{
        BlockDownloadingAlert, BlockFinishedAlert, BlockTimeoutAlert, BlockUploadedAlert,
        IncomingRequestAlert, InvalidRequestAlert, LsdPeerAlert, PeerBanAlert, PeerBlockedAlert,
        PeerConnectAlert, PeerDisconnectedAlert, PeerErrorAlert, PeerLogAlert, PeerSnubbedAlert,
        PeerUnsnubbedAlert, PickerLogAlert, RequestDroppedAlert, UnwantedBlockAlert,
    },
    ffi::ffi,
};

pub(super) struct PeerAlertRaw<'a>(*mut ffi::peer_alert, PhantomData<&'a ()>);

impl<'a> PeerAlertRaw<'a> {
    pub(crate) fn new(alert: *mut ffi::peer_alert) -> PeerAlertRaw<'a> {
        PeerAlertRaw(alert, PhantomData)
    }
}

pub enum PeerAlert {
    /// This alert is generated when a peer is banned because it has sent too many corrupt pieces
    /// to us. ``ip`` is the endpoint to the peer that was banned.
    ///
    /// ## Alert Category
    /// [`AlertCategory::Peer`]
    /// ## Alert Priority
    /// [`AlertPriority::Normal`]
    PeerBan(PeerBanAlert),
    /// This alert is generated when a peer is un-snubbed. Essentially when it was snubbed for stalling
    /// sending data, and now it started sending data again.
    ///
    /// ## Alert Category
    /// [`AlertCategory::Peer`]
    /// ## Alert Priority
    /// [`AlertPriority::Normal`]
    PeerUnsnubbed(PeerUnsnubbedAlert),
    /// This alert is generated when a peer is snubbed, when it stops sending data when we request
    /// it.
    ///
    /// ## Alert Category
    /// [`AlertCategory::Peer`]
    /// ## Alert Priority
    /// [`AlertPriority::Normal`]
    PeerSnubbed(PeerSnubbedAlert),
    /// This alert is generated when a peer sends invalid data over the peer-peer protocol. The peer
    /// will be disconnected, but you get its ip address from the alert, to identify it.
    ///
    /// ## Alert Category
    /// [`AlertCategory::Peer`]
    /// ## Alert Priority
    /// [`AlertPriority::Normal`]
    PeerError(PeerErrorAlert),
    /// This alert is posted every time an incoming peer connection both
    /// successfully passes the protocol handshake and is associated with a
    /// torrent, or an outgoing peer connection attempt succeeds. For arbitrary
    /// incoming connections, see incoming_connection_alert.
    ///
    /// ## Alert Category
    /// [`AlertCategory::Connect`]
    /// ## Alert Priority
    /// [`AlertPriority::Normal`]
    PeerConnect(PeerConnectAlert),
    /// This alert is generated when a peer is disconnected for any reason (other than the ones
    /// covered by [`PeerAlert::PeerError`]).
    ///
    /// ## Alert Category
    /// [`AlertCategory::Connect`]
    /// ## Alert Priority
    /// [`AlertPriority::Normal`]
    PeerDisconnected(PeerDisconnectedAlert),
    /// This is a debug alert that is generated by an incoming invalid piece request.
    /// ``ip`` is the address of the peer and the ``request`` is the actual incoming
    /// request from the peer. See peer_request for more info.
    ///
    /// ## Alert Category
    /// [`AlertCategory::Peer`]
    /// ## Alert Priority
    /// [`AlertPriority::Normal`]
    InvalidRequest(InvalidRequestAlert),
    /// This alert is generated when a peer rejects or ignores a piece request.
    ///
    /// ## Alert Category
    /// [`AlertCategory::BlockProgress`] [`AlertCategory::Peer`]
    /// ## Alert Priority
    /// [`AlertPriority::Normal`]
    RequestDropped(RequestDroppedAlert),
    /// This alert is generated when a block request times out.
    ///
    /// ## Alert Category
    /// [`AlertCategory::BlockProgress`] [`AlertCategory::Peer`]
    /// ## Alert Priority
    /// [`AlertPriority::Normal`]
    BlockTimeout(BlockTimeoutAlert),
    /// This alert is generated when a block request receives a response.
    ///
    /// ## Alert Category
    /// [`AlertCategory::BlockProgress`]
    /// ## Alert Priority
    /// [`AlertPriority::Normal`]
    BlockFinished(BlockFinishedAlert),
    /// This alert is generated when a block request is sent to a peer.
    ///
    /// ## Alert Category
    /// [`AlertCategory::BlockProgress`]
    /// ## Alert Priority
    /// [`AlertPriority::Normal`]
    BlockDownloading(BlockDownloadingAlert),
    /// This alert is generated when a block is received that was not requested or
    /// whose request timed out.
    ///
    /// ## Alert Category
    /// [`AlertCategory::Peer`]
    /// ## Alert Priority
    /// [`AlertPriority::Normal`]
    UnwantedBlock(UnwantedBlockAlert),
    /// This alert is posted when an incoming peer connection, or a peer that's about to be added
    /// to our peer list, is blocked for some reason. This could be any of:
    ///
    /// * the IP filter
    /// * i2p mixed mode restrictions (a normal peer is not allowed on an i2p swarm)
    /// * the port filter
    /// * the peer has a low port and ``no_connect_privileged_ports`` is enabled
    /// * the protocol of the peer is blocked (uTP/TCP blocking)
    ///
    /// ## Alert Category
    /// [`AlertCategory::IpBlock`]
    /// ## Alert Priority
    /// [`AlertPriority::Normal`]
    PeerBlocked(PeerBlockedAlert),
    /// This alert is generated when we receive a local service discovery message
    /// from a peer for a torrent we're currently participating in.
    ///
    /// ## Alert Category
    /// [`AlertCategory::Peer`]
    /// ## Alert Priority
    /// [`AlertPriority::Normal`]
    LsdPeer(LsdPeerAlert),
    /// This alert is posted by events specific to a peer. It's meant to be used
    /// for trouble shooting and debugging. It's not enabled by the default alert
    /// mask and is enabled by the [`AlertCategory::PeerLog`] bit. By
    /// default it is disabled as a build configuration.
    ///
    /// ## Alert Category
    /// [`AlertCategory::PeerLog`]
    /// ## Alert Priority
    /// [`AlertPriority::Normal`]
    PeerLog(PeerLogAlert),
    /// Posted every time an incoming request from a peer is accepted and queued
    /// up for being serviced. This alert is only posted if
    /// the AlertCategory::IncomingRequest flag is enabled in the alert
    /// mask.
    ///
    /// ## Alert Category
    /// [`AlertCategory::IncomingRequest`]
    /// ## Alert Priority
    /// [`AlertPriority::Normal`]
    IncomingRequest(IncomingRequestAlert),
    /// This is posted when one or more blocks are picked by the piece picker,
    /// assuming the verbose piece picker logging is enabled (see
    /// [`AlertCategory::PickerLog`]).
    ///
    /// ## Alert Category
    /// [`AlertCategory::PickerLog`]
    /// ## Alert Priority
    /// [`AlertPriority::Normal`]
    PickerLog(PickerLogAlert),
    /// This alert is posted when a block intended to be sent to a peer is placed in the
    /// send buffer. Note that if the connection is closed before the send buffer is sent,
    /// the alert may be posted without the bytes having been sent to the peer.
    ///
    /// ## Alert Category
    /// [`AlertCategory::Upload`]
    /// ## Alert Priority
    /// [`AlertPriority::Normal`]
    BlockUploaded(BlockUploadedAlert),
}
